const ALERT = "ALERT";
const REFETCH_CHATS = "REFETCH_CHATS";

const NEW_ATTACHMENT = "NEW_ATTACHMENT";
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";

const NEW_REQUEST = "NEW_REQUEST";
const NEW_MESSAGE = "NEW_MESSAGE";

const START_TYPING = "START_TYPING";
const STOP_TYPING = "STOP_TYPING";

const CHAT_JOINED = "CHAT_JOINED";
const CHAT_LEAVED = "CHAT_LEAVED";

const ONLINE_USERS = "ONLINE_USERS";

// Call Events
const CALL_INITIATED = "CALL_INITIATED";
const CALL_ACCEPTED = "CALL_ACCEPTED";
const CALL_REJECTED = "CALL_REJECTED";
const CALL_ENDED = "CALL_ENDED";
const CALL_UNAVAILABLE = "CALL_UNAVAILABLE";
const INCOMING_CALL = "INCOMING_CALL";
const WEBRTC_OFFER = "WEBRTC_OFFER";
const WEBRTC_ANSWER = "WEBRTC_ANSWER";
const WEBRTC_ICE_CANDIDATE = "WEBRTC_ICE_CANDIDATE";

export {
  ALERT,
  REFETCH_CHATS,
  NEW_ATTACHMENT,
  NEW_MESSAGE_ALERT,
  NEW_REQUEST,
  NEW_MESSAGE,
  START_TYPING,
  STOP_TYPING,
  CHAT_JOINED,
  CHAT_LEAVED,
  ONLINE_USERS,
  CALL_INITIATED,
  CALL_ACCEPTED,
  CALL_REJECTED,
  CALL_ENDED,
  CALL_UNAVAILABLE,
  INCOMING_CALL,
  WEBRTC_OFFER,
  WEBRTC_ANSWER,
  WEBRTC_ICE_CANDIDATE,
};
